## sentiment analyzer VADER
(https://github.com/cjhutto/vaderSentiment)
(http://datameetsmedia.com/vader-sentiment-analysis-explained/)

In [2]:
# remove 'RT' from tweet text
# might do sampling within each 10 minutes period

import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer

sid = SentimentIntensityAnalyzer()

def score(text):
    try: 
        ss = sid.polarity_scores(text)
        return ss['compound']
    except: 
        return 0

def remove_RT(text):
    index = text.find('RT')
    if index != -1:
        text = text[index+3:]
    return text

In [14]:
df_timeline = pd.read_csv('tesla_timeline_text.csv', dtype={'created_at':str, 'id_str':str})
df_timeline.fillna('', inplace=True)
df_timeline['text'] = df_timeline['text'].apply(remove_RT)
df_timeline['compound'] = df_timeline['text'].apply(score)
df_timeline['label'] = 'timeline'
df_timeline.head()

,created_at,favorite_count,id_str,retweet_count,followers_count,truncated,text,compound,label
0,03081334,26,1104088136630657024,4,1661635,True,Verizon is proud to support the mission to inc...,0.7964,timeline
1,03081154,36,1104062772546097155,6,1661635,True,All strong and powerful women start as girls w...,0.5106,timeline
2,03071311,0,1103719888902868992,0,1661635,False,,0.0000,timeline
3,03061537,42,1103394288187174913,28,1661635,True,We want to help those affected by the tornadoe...,0.6486,timeline
4,03061325,1,1103360868396478465,0,1661635,False,We re ready for ya Ash,0.3612,timeline

In [15]:
df_popular = pd.read_csv('tesla_popular_text.csv', dtype={'created_at':str, 'id_str':str})
df_popular.fillna('', inplace=True)
df_popular['text'] = df_popular['text'].apply(remove_RT)
df_popular['compound'] = df_popular['text'].apply(score)
df_popular['label'] = 'popular'
df_popular.head()

,created_at,favorite_count,id_str,retweet_count,followers_count,truncated,text,compound,label
0,03081401,299,1104094893276913665,54,1811873,False,This is home to me In this insider explains wh...,0.0000,popular
1,02281111,1128,1101152964217978880,679,410111,True,ANNOUNCING a new way to show companies we re s...,0.2732,popular
2,03051209,97,1102979357881131008,88,98057,True,It s imperative every member of Congress regar...,0.4019,popular
3,03060906,1382,1103295892067504129,148,6177284,True,Getting a spam call is almost as bad as having...,-0.6151,popular
4,03060228,739,1103195508665929731,79,5965147,False,The Dubs fall to the Celtics at home brings yo...,0.5994,popular

In [16]:
df_mixed = pd.read_csv('tesla_mixed_text.csv', dtype={'created_at':str, 'id_str':str})
df_mixed.fillna('', inplace=True)
df_mixed['text'] = df_mixed['text'].apply(remove_RT)
df_mixed['compound'] = df_mixed['text'].apply(score)
df_mixed['label'] = 'mixed'
df_mixed.head()

,created_at,favorite_count,id_str,retweet_count,followers_count,truncated,text,compound,label
0,03081504,284,1104110574932127744,66,2419,True,is now playing on these platforms and more Alt...,0.2023,mixed
1,03081401,331,1104094893276913665,59,1811911,False,This is home to me In this insider explains wh...,0.0000,mixed
2,03080815,70,1104007610364121088,33,11414799,True,This International Women s Day CARE and Verizo...,0.7531,mixed
3,03090026,0,1104252030766333952,10836,121,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
4,03090026,0,1104251998210265088,10836,349,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed

In [17]:
df = pd.concat([df_timeline, df_popular, df_mixed])
df = df.drop_duplicates(subset=['id_str'])
df = df.sort_values(by=['created_at'], ascending=False)
df

,created_at,favorite_count,id_str,retweet_count,followers_count,truncated,text,compound,label
3,03090026,0,1104252030766333952,10836,121,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
4,03090026,0,1104251998210265088,10836,349,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
5,03090026,0,1104251981521145858,10836,840,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
17,03090025,0,1104251725593030657,10836,140,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
16,03090025,0,1104251764415627264,10836,268,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
6,03090025,0,1104251968623706112,10836,906,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
7,03090025,0,1104251948809814016,10836,340,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
8,03090025,0,1104251880446849024,10836,358,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
9,03090025,0,1104251872322379777,10836,4416,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
10,03090025,0,1104251837908221952,10836,380,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
12,03090025,0,1104251818920603648,10836,457,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
13,03090025,0,1104251811731525632,10836,293,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
14,03090025,0,1104251807608565760,10836,2401,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
15,03090025,0,1104251803212881920,10836,425,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
11,03090025,0,1104251824771686401,10836,192,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
24,03090024,0,1104251531103211524,10836,597,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
19,03090024,0,1104251570680725504,10836,606,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
20,03090024,0,1104251562279481345,10836,410,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
21,03090024,0,1104251555958611968,10836,426,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
22,03090024,0,1104251552649211904,10836,400,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
23,03090024,0,1104251549717540866,10836,39,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
25,03090024,0,1104251523201036288,10836,574,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
26,03090024,0,1104251471896420352,10836,738,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
27,03090024,0,1104251466653421569,66,279,False,is now playing on these platforms and more Alt...,0.2023,mixed
18,03090024,0,1104251629367377920,10836,365,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
41,03090023,0,1104251270754430976,10836,201,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
39,03090023,0,1104251298935984128,10836,322,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
40,03090023,0,1104251283236626432,10836,430,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
32,03090023,0,1104251393324523520,0,340,False,Should of ordered the galaxy through Verizon a...,0.0000,mixed
37,03090023,0,1104251327155224576,10836,308,False,Verizon You re all out of data You ve been cha...,-0.2023,mixed
...,...,...,...,...,...,...,...,...,...
33076,02281851,2,1101268811901255681,1,683,False,I saw a tweet that said if you have Sprint you...,0.3818,mixed
33084,02281850,1,1101268383985778688,0,3143,True,I get these EVERY DAY I just want them to stop...,-0.2263,mixed
33083,02281850,0,1101268476847710208,4,69278,False,We ve got some exciting news Robocaller days a...,0.4939,mixed
33085,02281849,0,1101268291748839424,0,249235,True,I rely on a solid signal at all times especial...,0.5106,mixed
33086,02281849,3,1101268211776086016,2,1120,True,BTS tickets TEST YOUR AVAILABLE INTERNET CONNE...,0.0000,mixed
33089,02281848,0,1101267853196623872,0,247,False,Submit SPRINT VERIZON AT amp T POSTPAID FOR XS...,0.0000,mixed
33087,02281848,0,1101268049867522048,2,30,False,Verizon can choose their largest or toughest e...,-0.7783,mixed
33090,02281848,0,1101267820611018757,6,285,False,We re here at the Breakfast kicking off the Tr...,0.0000,mixed
33088,02281848,0,1101267936961089537,0,66,True,,0.0000,mixed
33092,02281847,1,1101267587802062848,0,104,True,I m on Morris Essex and find that my phone consta,0.0000,mixed
33091,02281847,0,1101267709181001728,0,6,True,At least your getting them from various area c...,0.0000,mixed
33096,02281846,0,1101267308109017088,0,13,False,Thankfully Verizon only has control over our i...,0.4215,mixed
33095,02281846,0,1101267338677104640,0,17,False,a keyboard smash is far less effective on the ...,0.4228,mixed
33094,02281846,0,1101267479353933824,0,1747,False,Now THAT gives me Goosebumps,0.0000,mixed
33093,02281846,0,1101267489177112576,65,380,False,Everyone has their own mission Ours happens to...,0.3400,mixed
33097,02281845,0,1101267290157445120,0,2605,False,Taken place immediately It appears as though V...,0.0772,mixed
33098,02281845,0,1101267281974382592,0,184,True,Hey Verizon I can t get through to prepaid sup...,0.4019,mixed
33099,02281845,0,1101267238873518080,0,137,False,Pass Rusher Jenny V,0.0000,mixed
25,02281724,48,1101246859157356544,10,1661635,True,No lines just access Reality is better than ex...,0.6808,timeline
9,02281443,383,1101206307741130752,57,22707,True,Lots of famous conspiracy theories out there b...,-0.2960,popular
26,02281321,0,1101185517041926145,19,1661635,False,celebrates with a performance by a fireside ch...,0.5719,timeline
27,02281300,30,1101180229396004864,9,1661635,True,We re so proud to have created the first ad to...,0.7177,timeline
13,02281300,29,1101180296865738753,19,11414574,True,celebrates with a performance by a fireside ch...,0.5719,popular
1,02281111,1128,1101152964217978880,679,410111,True,ANNOUNCING a new way to show companies we re s...,0.2732,popular
28,02281025,1,1101141246691684352,0,1661635,False,We ve got you Reezy,0.0000,timeline
24,02281007,172,1101136782341664768,24,6177284,False,Do you think this is how and come up with thei...,0.0000,popular
7,02272310,669,1100971549127958534,88,5965147,False,Dubs comeback falls just short has it all in t...,-0.5423,popular
8,02272043,257,1100934359480188929,74,1217159,False,he s cooking again leads the team with 2 0 poi...,0.0000,popular
29,02271802,1,1100893854201532417,0,1661635,False,We re not going to try,0.0000,timeline
88,02271056,26,1100786655408111616,37,36842,False,Large outage appears to be targeting Verizon W...,0.3612,popular

In [18]:
df.to_csv('tesla.csv', index=False)